apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1


      - name: Set Version
        id: set-tag
        uses: docker://fedora:39
        shell: sh
        run: |
          dnf install -y git > /dev/null
          DATE=`date '+%y%m%d'`
          HASH=`git rev-parse --short HEAD`
          echo "Working on tag ~${DATE}.${HASH}~"
          echo -n "${DATE}.${HASH}" >> "$CLOUDBEES_OUTPUTS/version_tag" 

      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean compile

      - name: Scan with SonarQube bundled action
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: LANGUAGE_JAVA
          sonar-inclusion: /cloudbees/workspace/target/classes
          threshold-critical: 0
          log-level: DEBUG
        kind: scan
        
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build a container image with Kaniko
      #   uses: cloudbees-io/kaniko@v1
      #   with:
      #     dockerfile: Dockerfile
      #     context: .
      #     destination: rbroker/petclinic-app:${{steps.set-tag.outputs.version_tag}},rbroker/petclinic-app:latest
      #     build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1

      # - name: Start CDRO Pipeline
      #   uses: zvercodebender/cdro-action@v0.2
      #   with:
      #     url: ${{vars.CB_FLOW}}
      #     username: ${{secrets.CB_USER}}
      #     user-token: ${{secrets.CB_PASSWD}}
      #     project-name: MyProject
      #     release-name: Petclinic-Release
      #     parameters: '{\"pipelineParameter\":[{\"pipelineParameterName\":\"appVersion\",\"value\":\"${{steps.set-tag.outputs.version_tag}}\"}]}'

      - uses: cloudbees-io/publish-evidence-item@v1
        name: Third evidence step
        with:
          content: |-
            # Table
            | Container |
            | rbroker/hello-py:${{steps.set-tag.outputs.version_tag}} |

