apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Set Version
        id: set-tag
        uses: docker://fedora:39
        shell: sh
        run: |
          dnf install -y git > /dev/null
          DATE=`date '+%y%m%d'`
          HASH=`git rev-parse --short HEAD`
          echo "Working on tag ~${DATE}.${HASH}~"
          echo -n "${DATE}.${HASH}" >> "$CLOUDBEES_OUTPUTS/version_tag" 
      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean compile
      - name: Scan with SonarQube bundled action
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          language: LANGUAGE_JAVA
          sonar-inclusion: /cloudbees/workspace/target/classes
          threshold-critical: 0
        kind: scan
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Sonar Report
        id: get-sonar-data
        uses: docker://fedora:39
        shell: sh
        run: >
          cat /cloudbees/workspace/.scannerwork/report-task.txt >>
          "$CLOUDBEES_OUTPUTS/sonar_report" 

          cat /cloudbees/workspace/.scannerwork/report-task.txt
      - uses: cloudbees-io/publish-evidence-item@v1
        name: Third evidence step
        with:
          content: |-
            # Table
            | Container |
            |-----------|
            | rbroker/hello-py:${{steps.set-tag.outputs.version_tag}} |

            ```
            ${{steps.get-sonar-data.outputs.sonar_report}}
            ```
  deploy_to_dev:
    environment: DEV
    steps:
      - uses: docker://fedora:39
        name: DEPLOY_TO_DEV
        shell: sh
        run: |
          echo "Deploy to DEV"
    needs:
      - build-and-publish
