apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1


      - name: Set Version
        id: set-tag
        uses: docker://fedora:39
        shell: sh
        run: |
          dnf install -y git
          DATE=`date '+%y%m%d'`
          HASH=`git rev-parse --short HEAD`
          echo "Working on tag ~${DATE}.${HASH}~"
          echo "${DATE}.${HASH}" >> "$CLOUDBEES_OUTPUTS/version_tag" 

      - name: Get Version
        uses: docker://fedora:39
        shell: sh
        run: |
          echo "Working on tag ~${{ steps.set-tag.outputs.version_tag }}~"

      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean compile

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: rbroker/petclinic-app:${{steps.set-tag.outputs.version_tag}},rbroker/petclinic-app:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1

      # - name: Start CDRO Pipeline
      #   uses: docker://fedora:39
      #   shell: sh
      #   run: |
      #     curl -k -X POST "${{vars.CB_FLOW}}/rest/v1.0/releases?projectName=MyProject&releaseName=Petclinic-Release" \
      #     -u ${{secrets.CB_USER}}:${{secrets.CB_PASSWD}} \
      #     -H "accept: application/json" \
      #     -d "{\"pipelineParameter\":[{\"pipelineParameterName\":\"appVersion\",\"value\":\"${{steps.setTag.outputs.VARVERSION_TAGNAME}}}\"}]}"